name: Print Message
on:
  push:
    branches:
      -main
      -master
jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo"hello! A push detected on main branch"

      - name: Print a Message
        run: echo "Hello! A second push detected on main branch" 
